#!/bin/bash
SCRIPT_FOLDER="$HOME/.scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
	echo ERROR: FILE ALREADY EXISTS
else
	echo "#!/bin/bash" > $SCRIPT_FILE
	chmod +x $SCRIPT_FILE
	code $SCIPT_FILE
fi
